[package]
name = "fdo-serviceinfo-api-server"
version = "0.4.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
config = "0.13.3"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
log = "0.4"
serde = "1"
serde_bytes = "0.11"
serde_json = "1"
hyper = "0.14.23"
openssl = "0.10.45"
simple-hyper-server-tls = {version = "0.3.2" , features = ["tls-openssl"] }
axum = "0.6.4"
tower = "0.4.13"

fdo-http-wrapper = { path = "../http-wrapper", version = "0.4.7", features = ["server"] }
fdo-data-formats = { path = "../data-formats", version = "0.4.7" }
fdo-store = { path = "../store", version = "0.4.7", features = ["directory"] }
fdo-util = { path = "../util", version = "0.4.7" }
